### ISSUE TITLE
Kinja API updates

### ISSUE THREAD

**Issue by balagez** [Ainlaen/kinjamprove_continued#1]
Hey, Kinja dev here. Can you please stop sending tokens in the URL and the request payload? The `Authorization` header alone should work and we will soon start blocking request that send the token elsewhere. Thanks!

**Comment by Ainlaen** [comment]
All the normal user API requests should be solely using the Authorization header now. Everything else will be switched over in the next version.
Thanks for the heads up.

**Comment by Ainlaen** [comment]
Unless I missed something, 0.0.2.14 should have this resolved.
